### ISSUE TITLE
A Load-more Function

### ISSUE THREAD

**Issue by teaware** [colbyfayock/egghead-code-examples#9]
I'm not familiar with the `gatsby-node.js`, and I want a load-more function.
I have no idea how I'm gonna do that. Please help 🥺

**Comment by teaware** [comment]
[link here](https://github.com/colbyfayock/egghead-code-examples/blob/33fa85cad5376e216343733b5ecd1e4b98ee09e5/collection-source-and-create-nodes-with-data-from-an-api-in-gatsby/07-add-cutout-notch-html-element-css-polygon-clip-path/gatsby-node.js)

**Comment by colbyfayock** [comment]
hey @teaware have you checked out Gatsby's docs that walk through it?

https://www.gatsbyjs.com/docs/adding-pagination/

There's also a tutorial here:

https://nickymeuleman.netlify.app/blog/gatsby-pagination

**Comment by teaware** [comment]
Thank you!
